# Generated by Django 5.0.6 on 2024-06-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_models', '0005_jobannouncments'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dynamic_images/', verbose_name='Dynamic Image(static)')),
            ],
        ),
        migrations.AlterField(
            model_name='jobannouncments',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
