# Generated by Django 5.0.6 on 2024-06-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_models', '0006_dynamicimage_alter_jobannouncments_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Logo_images/', verbose_name='Logo Image(static)')),
            ],
        ),
    ]
